# Generated by Django 5.2.17 on 2026-08-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.CharField(max_length=120, verbose_name="목적지 도시"),
                ),
                (
                    "destination_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=8,
                        verbose_name="도시/공항 코드",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="여행 시작일")),
                ("end_date", models.DateField(verbose_name="여행 종료일")),
                (
                    "date_source",
                    models.CharField(
                        choices=[("flight", "항공권 기반"), ("manual", "날짜만 등록")],
                        default="manual",
                        max_length=10,
                        verbose_name="날짜 출처",
                    ),
                ),
                (
                    "flight_info",
                    models.JSONField(blank=True, null=True, verbose_name="항공권 정보"),
                ),
            ],
            options={
                "verbose_name": "여행",
                "verbose_name_plural": "여행",
                "ordering": ("-start_date", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="trip_end_date_gte_start_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="숙소명")),
                ("address", models.CharField(max_length=255, verbose_name="주소")),
                ("check_in", models.DateField(verbose_name="체크인")),
                (
                    "check_out",
                    models.DateField(blank=True, null=True, verbose_name="체크아웃"),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "숙소",
                "verbose_name_plural": "숙소",
                "ordering": ("check_in", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("check_out__isnull", True),
                            ("check_out__gte", models.F("check_in")),
                            _connector="OR",
                        ),
                        name="hotel_check_out_gte_check_in",
                    )
                ],
            },
        ),
    ]
