# Generated by Django 5.2.17 on 2026-09-24 12:19

from django.db import migrations, models


def forwards(apps, schema_editor):
    """destination/destination_code(단일 도시) -> destinations(다중 여행지 목록)."""
    Trip = apps.get_model("trips", "Trip")
    for trip in Trip.objects.exclude(destination="").iterator():
        trip.destinations = [
            {"city": trip.destination, "city_code": trip.destination_code or ""}
        ]
        trip.save(update_fields=["destinations"])


def backwards(apps, schema_editor):
    """첫 번째 여행지만 단일 필드로 되돌린다(2번째 이후 도시는 유실)."""
    Trip = apps.get_model("trips", "Trip")
    for trip in Trip.objects.iterator():
        first = (trip.destinations or [{}])[0]
        trip.destination = first.get("city", "")
        trip.destination_code = first.get("city_code", "")
        trip.save(update_fields=["destination", "destination_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="destinations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"city": "도시명", "city_code": "도시코드"}] 형태의 목록',
                verbose_name="여행지",
            ),
        ),
        # 컬럼을 지우기 전에 기존 값을 옮긴다.
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="trip",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="destination_code",
        ),
    ]
