# Generated by Django 5.2.17 on 2026-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=100, verbose_name='국문 항공사명')),
                ('iata_code', models.CharField(max_length=2, unique=True, verbose_name='iata 코드')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='국가')),
            ],
            options={
                'verbose_name': '항공사',
                'verbose_name_plural': '항공사',
                'ordering': ('name_ko',),
            },
        ),
    ]
