# Generated by Django 5.2.17 on 2026-09-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city_code',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='도시코드'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='place_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Google Place ID'),
        ),
    ]
