# Generated by Django 5.2.17 on 2026-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='color',
            field=models.CharField(blank=True, choices=[('indigo', '인디고'), ('red', '빨강'), ('orange', '주황'), ('yellow', '노랑'), ('green', '초록'), ('blue', '파랑'), ('purple', '보라'), ('gray', '회색')], default='', max_length=10, verbose_name='색상'),
        ),
    ]
