# Generated by Django 5.2.17 on 2026-10-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='itinerary_initialized',
            field=models.BooleanField(default=False, verbose_name='일정 초기화 여부'),
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(verbose_name='날짜')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('kind', models.CharField(choices=[('flight', '항공편'), ('hotel', '숙소'), ('airport', '공항'), ('sight', '관광지'), ('restaurant', '식당'), ('cafe', '카페')], max_length=12, verbose_name='유형')),
                ('source', models.CharField(choices=[('auto', '항공편·숙소'), ('manual', '직접 추가'), ('ai', 'AI 추천')], default='manual', max_length=8, verbose_name='추가 방법')),
                ('title', models.CharField(max_length=150, verbose_name='이름')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='시간')),
                ('time_label', models.CharField(blank=True, default='', max_length=20, verbose_name='시간 표기')),
                ('subtitle', models.CharField(blank=True, default='', max_length=100, verbose_name='부가 설명')),
                ('stops', models.JSONField(blank=True, default=list, verbose_name='위치')),
                ('place_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Google Place ID')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='주소')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='전화번호')),
                ('opening_hours', models.JSONField(blank=True, default=list, verbose_name='영업시간')),
                ('memo', models.TextField(blank=True, default='', verbose_name='메모')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='trips.trip')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정',
                'ordering': ('day', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=200, verbose_name='내용')),
                ('done', models.BooleanField(default=False, verbose_name='완료')),
                ('in_packing_note', models.BooleanField(default=False, verbose_name='짐싸기 노트 표시')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='trips.itineraryitem')),
            ],
            options={
                'verbose_name': '체크리스트',
                'verbose_name_plural': '체크리스트',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
