# Generated by Django 5.2.17 on 2026-10-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='전화번호'),
        ),
    ]
