# 도시 키를 IATA 도시 코드에서 서비스 자체 도시 id로 바꾼다.
# - 숙소 도시 코드 칸을 32자로 늘리고
# - 저장된 여행지(Trip.destinations)·숙소(Hotel.city_code)의 IATA 도시 코드를 도시 id로 바꾼다.
# 변환표는 이 시점의 backend/data/cities.json 기준으로 고정해 둔다(데이터 파일이 바뀌어도 이 마이그레이션은 그대로).
# Generated by Django 5.2.17 on 2026-10-07 11:16

from django.db import migrations, models

IATA_TO_CITY_ID = {
    "SEL": "seoul", "PUS": "busan", "CJU": "jeju", "TYO": "tokyo", "OSA": "osaka", "NGO": "nagoya",
    "FUK": "fukuoka", "SPK": "sapporo", "OKA": "okinawa", "SDJ": "sendai", "HIJ": "hiroshima", "KOJ": "kagoshima",
    "TAK": "takamatsu", "BJS": "beijing", "SHA": "shanghai", "CAN": "guangzhou", "TAO": "qingdao", "SIA": "xian",
    "HKG": "hong-kong", "MFM": "macau", "TPE": "taipei", "KHH": "kaohsiung", "BKK": "bangkok", "CNX": "chiang-mai",
    "HKT": "phuket", "SIN": "singapore", "KUL": "kuala-lumpur", "BKI": "kota-kinabalu", "HAN": "hanoi", "SGN": "ho-chi-minh-city",
    "DAD": "da-nang", "CXR": "nha-trang", "PQC": "phu-quoc", "MNL": "manila", "CEB": "cebu", "MPH": "boracay",
    "DPS": "bali", "JKT": "jakarta", "PNH": "phnom-penh", "REP": "siem-reap", "VTE": "vientiane", "RGN": "yangon",
    "DEL": "delhi", "BOM": "mumbai", "KTM": "kathmandu", "CMB": "colombo", "MLE": "male", "ULN": "ulaanbaatar",
    "ALA": "almaty", "TAS": "tashkent", "DXB": "dubai", "AUH": "abu-dhabi", "DOH": "doha", "IST": "istanbul",
    "TLV": "tel-aviv", "PAR": "paris", "LON": "london", "ROM": "rome", "MIL": "milan", "VCE": "venice",
    "FLR": "florence", "NAP": "naples", "BCN": "barcelona", "MAD": "madrid", "LIS": "lisbon", "OPO": "porto",
    "AMS": "amsterdam", "BRU": "brussels", "BER": "berlin", "MUC": "munich", "FRA": "frankfurt", "PRG": "prague",
    "VIE": "vienna", "BUD": "budapest", "ZRH": "zurich", "GVA": "geneva", "CPH": "copenhagen", "STO": "stockholm",
    "OSL": "oslo", "HEL": "helsinki", "REK": "reykjavik", "DUB": "dublin", "EDI": "edinburgh", "ATH": "athens",
    "WAW": "warsaw", "ZAG": "zagreb", "DBV": "dubrovnik", "MOW": "moscow", "NYC": "new-york", "LAX": "los-angeles",
    "SFO": "san-francisco", "LAS": "las-vegas", "SEA": "seattle", "CHI": "chicago", "WAS": "washington-dc", "BOS": "boston",
    "MIA": "miami", "ORL": "orlando", "HNL": "honolulu", "YVR": "vancouver", "YTO": "toronto", "MEX": "mexico-city",
    "CUN": "cancun", "SAO": "sao-paulo", "RIO": "rio-de-janeiro", "BUE": "buenos-aires", "LIM": "lima", "SYD": "sydney",
    "MEL": "melbourne", "BNE": "brisbane", "OOL": "gold-coast", "CNS": "cairns", "AKL": "auckland", "ZQN": "queenstown",
    "GUM": "guam", "SPN": "saipan", "NAN": "nadi", "CAI": "cairo", "CPT": "cape-town", "JNB": "johannesburg",
    "NBO": "nairobi", "RAK": "marrakech",
}


def to_city_ids(apps, schema_editor):
    Trip = apps.get_model("trips", "Trip")
    Hotel = apps.get_model("trips", "Hotel")
    for trip in Trip.objects.all():
        destinations = trip.destinations or []
        changed = False
        for dest in destinations:
            new = IATA_TO_CITY_ID.get((dest.get("city_code") or "").upper())
            if new and dest.get("city_code") != new:
                dest["city_code"] = new
                changed = True
        if changed:
            trip.save(update_fields=["destinations"])
    for iata, city_id in IATA_TO_CITY_ID.items():
        Hotel.objects.filter(city_code__iexact=iata).update(city_code=city_id)


def to_iata(apps, schema_editor):
    Trip = apps.get_model("trips", "Trip")
    Hotel = apps.get_model("trips", "Hotel")
    city_id_to_iata = {city_id: iata for iata, city_id in IATA_TO_CITY_ID.items()}
    for trip in Trip.objects.all():
        destinations = trip.destinations or []
        for dest in destinations:
            dest["city_code"] = city_id_to_iata.get(dest.get("city_code") or "", dest.get("city_code") or "")[:8]
        trip.save(update_fields=["destinations"])
    for city_id, iata in city_id_to_iata.items():
        Hotel.objects.filter(city_code=city_id).update(city_code=iata)


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_clear_place_kind_subtitle'),
    ]

    operations = [
        # 칸을 먼저 늘린 뒤 값을 바꾼다(도시 id는 8자를 넘을 수 있다). 되돌릴 때는 값을 먼저 되돌린다.
        migrations.AlterField(
            model_name='hotel',
            name='city_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='도시코드'),
        ),
        migrations.RunPython(to_city_ids, to_iata),
    ]
