/**
 * 항공사 자동완성 목록. `scripts/generate_airlines.py`가 생성하므로 직접 수정하지 않는다.
 * 원본: backend/data/airlines.csv (영문명은 스크립트의 ENGLISH_NAMES에서 보완)
 *
 * code: IATA 항공사 코드 (편명 앞에 붙는 2자리)
 * name: 국문 항공사명
 * name_en: 주요 항공사에만 존재. 없으면 한글명과 코드로만 검색된다.
 */

export interface AirlineOption {
  /** IATA 항공사 코드 (2자리) */
  code: string;
  /** 국문 항공사명 */
  name: string;
  /** 영문 항공사명 (주요 항공사만) */
  name_en?: string;
}

export const AIRLINES: AirlineOption[] = [
  {"code": "2I", "name": "21 에어"},
  {"code": "Q5", "name": "40 마일 에어"},
  {"code": "FE", "name": "748 항공서비스"},
  {"code": "AQ", "name": "9 에어"},
  {"code": "GB", "name": "ABX 에어"},
  {"code": "K4", "name": "ALS 리미티드"},
  {"code": "3V", "name": "ASL 벨기에 항공"},
  {"code": "5O", "name": "ASL 프랑스 항공"},
  {"code": "4A", "name": "ATSA 페루"},
  {"code": "CJ", "name": "BA 시티플라이어"},
  {"code": "A0", "name": "BA 유로플라이어"},
  {"code": "B5", "name": "BBN 항공"},
  {"code": "8H", "name": "BH 에어"},
  {"code": "H5", "name": "CM 항공"},
  {"code": "2C", "name": "CMA CGM 화물항공"},
  {"code": "OK", "name": "CSA 체코 항공"},
  {"code": "DX", "name": "DAT 항공"},
  {"code": "L3", "name": "DHL 과테말라"},
  {"code": "ES", "name": "DHL 국제항공 ME"},
  {"code": "D0", "name": "DHL 에어 영국"},
  {"code": "Q7", "name": "DHL 에어 오스트리아"},
  {"code": "D5", "name": "DHL 에어로 익스프레스"},
  {"code": "7T", "name": "DHL 에콰도르"},
  {"code": "LI", "name": "ETF 항공"},
  {"code": "8D", "name": "FITS 항공"},
  {"code": "C0", "name": "FTL항공"},
  {"code": "IV", "name": "GP 항공"},
  {"code": "II", "name": "IBC 항공"},
  {"code": "AZ", "name": "ITA항공"},
  {"code": "XE", "name": "JSX 항공"},
  {"code": "FK", "name": "KF 카고"},
  {"code": "KL", "name": "KLM 네덜란드 항공", "name_en": "KLM"},
  {"code": "KK", "name": "LEAV 항공"},
  {"code": "LO", "name": "LOT 폴란드 항공", "name_en": "LOT Polish Airlines"},
  {"code": "WW", "name": "M 제트 인터내셔널"},
  {"code": "M2", "name": "MHS 항공"},
  {"code": "OM", "name": "MIAT 몽골 항공"},
  {"code": "6V", "name": "MRK 항공"},
  {"code": "PB", "name": "PAL 항공 캐나다"},
  {"code": "CG", "name": "PNG 항공"},
  {"code": "OH", "name": "PSA 항공"},
  {"code": "RZ", "name": "SANSA 항공"},
  {"code": "SK", "name": "SAS 랑공", "name_en": "SAS"},
  {"code": "SL", "name": "SAS 연결", "name_en": "Thai Lion Air"},
  {"code": "SP", "name": "SATA 에어 아조레스"},
  {"code": "O3", "name": "SF 항공"},
  {"code": "KI", "name": "SKS 항공"},
  {"code": "S0", "name": "SOSA 항공"},
  {"code": "8F", "name": "STP 항공"},
  {"code": "DT", "name": "TAAG 항공"},
  {"code": "T0", "name": "TACA 페루"},
  {"code": "TP", "name": "TAP 익스프레스", "name_en": "TAP Air Portugal"},
  {"code": "RO", "name": "TAROM 항공"},
  {"code": "X3", "name": "TUI 플라이"},
  {"code": "6B", "name": "TUI 플라이 노르딕"},
  {"code": "TB", "name": "TUI 플라이 벨기에"},
  {"code": "5X", "name": "UPS"},
  {"code": "UJ", "name": "USA 제트 항공"},
  {"code": "RT", "name": "UVT 항공"},
  {"code": "GA", "name": "가루다 인도네시아 항공", "name_en": "Garuda Indonesia"},
  {"code": "G2", "name": "걸리버 항공"},
  {"code": "IF", "name": "걸프앤캐리비안항공"},
  {"code": "GF", "name": "걸프항공", "name_en": "Gulf Air"},
  {"code": "GW", "name": "겟젯 항공"},
  {"code": "JS", "name": "고려항공"},
  {"code": "G7", "name": "고젯 항공"},
  {"code": "6G", "name": "고투스카이"},
  {"code": "G3", "name": "골 항공"},
  {"code": "Y5", "name": "골든 미얀마 항공"},
  {"code": "G1", "name": "골든베이 항공"},
  {"code": "GX", "name": "광시 베이부 걸프 항공"},
  {"code": "YR", "name": "그랜드캐년 항공"},
  {"code": "GV", "name": "그랜트 항공"},
  {"code": "HB", "name": "그레이터 베이 항공"},
  {"code": "Q9", "name": "그린아프리카 항공"},
  {"code": "Z5", "name": "글로벌 아프리카 항공"},
  {"code": "G6", "name": "글로벌 크로싱 항공"},
  {"code": "GE", "name": "글로벌 항공 운영"},
  {"code": "ON", "name": "나우루 항공"},
  {"code": "NJ", "name": "나제르 항공"},
  {"code": "NM", "name": "나티레바 에어 모아나"},
  {"code": "IN", "name": "남 에어"},
  {"code": "SA", "name": "남아프리카 항공", "name_en": "South African Airways"},
  {"code": "9Y", "name": "내셔널 항공"},
  {"code": "NA", "name": "네스마 사우디아라비아 항공"},
  {"code": "NE", "name": "네스마 이집트 항공"},
  {"code": "NO", "name": "네오스 항공"},
  {"code": "RA", "name": "네팔 항공"},
  {"code": "1I", "name": "넷제트"},
  {"code": "NC", "name": "노던 에어 카고"},
  {"code": "Y7", "name": "노드스타 항공"},
  {"code": "N4", "name": "노드윈드 항공"},
  {"code": "ND", "name": "노르디카"},
  {"code": "N7", "name": "노르딕 리저널 항공"},
  {"code": "Z0", "name": "노르스 애틀랜틱 영국"},
  {"code": "N0", "name": "노르스 애틀랜틱 항공"},
  {"code": "DY", "name": "노르웨이 항공 셔틀 AOC"},
  {"code": "D8", "name": "노르웨이 항공 스웨덴 AOC"},
  {"code": "NG", "name": "노바 항공 아르메니아"},
  {"code": "VQ", "name": "노보에어"},
  {"code": "0N", "name": "노스 스타 에어카고"},
  {"code": "HW", "name": "노스라이트 항공"},
  {"code": "J3", "name": "노스웨스턴 에어 리스"},
  {"code": "DD", "name": "녹 에어"},
  {"code": "N5", "name": "놀리노르 항공"},
  {"code": "BJ", "name": "누벨레어 튀니지"},
  {"code": "EJ", "name": "뉴 잉글랜드 항공"},
  {"code": "OJ", "name": "닉스 에어"},
  {"code": "DN", "name": "단에어"},
  {"code": "D3", "name": "달로 항공"},
  {"code": "KE", "name": "대한항공", "name_en": "Korean Air"},
  {"code": "DL", "name": "델타항공", "name_en": "Delta Air Lines"},
  {"code": "ZQ", "name": "독일 항공"},
  {"code": "3R", "name": "디비 디비 에어"},
  {"code": "DF", "name": "디어제트항공"},
  {"code": "LC", "name": "라 코스테나"},
  {"code": "B0", "name": "라 콤페니"},
  {"code": "R4", "name": "라노 에어"},
  {"code": "LK", "name": "라오스 스카이웨이"},
  {"code": "QV", "name": "라오스 항공"},
  {"code": "7S", "name": "라이언 에어서비스"},
  {"code": "FR", "name": "라이언에어", "name_en": "Ryanair"},
  {"code": "RK", "name": "라이언에어 영국"},
  {"code": "JT", "name": "라이온 항공"},
  {"code": "8V", "name": "라이트 에어 서비스"},
  {"code": "UC", "name": "라탐 카고 칠레"},
  {"code": "L7", "name": "라탐 카고 콜롬비아"},
  {"code": "LA", "name": "라탐 항공"},
  {"code": "JJ", "name": "라탐 항공 브라질"},
  {"code": "XL", "name": "라탐 항공 에콰도르"},
  {"code": "4C", "name": "라탐 항공 콜롬비아"},
  {"code": "PZ", "name": "라탐 항공 파라과이"},
  {"code": "LP", "name": "라탐 항공 페루"},
  {"code": "TM", "name": "람 모잠비크 항공"},
  {"code": "BN", "name": "럭스윙"},
  {"code": "8L", "name": "럭키 에어"},
  {"code": "WZ", "name": "레더윙즈"},
  {"code": "L5", "name": "레드 에어"},
  {"code": "7H", "name": "레이븐 알라스카"},
  {"code": "R0", "name": "레인도 유나이티드서비스"},
  {"code": "LM", "name": "로간에어"},
  {"code": "FV", "name": "로시야 항공"},
  {"code": "AT", "name": "로얄 모로코 항공"},
  {"code": "RW", "name": "로얄 에어 필리핀"},
  {"code": "RJ", "name": "로얄 요르단 항공"},
  {"code": "RG", "name": "로타나 제트 항공"},
  {"code": "L9", "name": "루미윙스"},
  {"code": "5R", "name": "루타카 항공"},
  {"code": "LH", "name": "루프트한자", "name_en": "Lufthansa"},
  {"code": "CL", "name": "루프트한자 시티라인"},
  {"code": "VL", "name": "루프트한자시티항공"},
  {"code": "LG", "name": "룩스에어"},
  {"code": "GJ", "name": "룽 항공"},
  {"code": "LT", "name": "룽장 항공"},
  {"code": "WB", "name": "르완다 항공"},
  {"code": "YL", "name": "리비아 윙스"},
  {"code": "4P", "name": "리저널 스카이"},
  {"code": "8N", "name": "리저널 항공 서비스"},
  {"code": "F2", "name": "리저널 화물"},
  {"code": "L2", "name": "린든 항공화물"},
  {"code": "RI", "name": "림분 에어"},
  {"code": "FC", "name": "링크 항공"},
  {"code": "DI", "name": "마라부"},
  {"code": "O8", "name": "마라톤 항공"},
  {"code": "MP", "name": "마르틴에어"},
  {"code": "4M", "name": "마비곡 항공"},
  {"code": "M7", "name": "마스"},
  {"code": "MY", "name": "마스윙스"},
  {"code": "2M", "name": "마야 아일랜드 항공"},
  {"code": "2Y", "name": "마이 인도 항공"},
  {"code": "C6", "name": "마이 프라이터 항공"},
  {"code": "MJ", "name": "마이웨이 항공"},
  {"code": "9T", "name": "마이카고항공"},
  {"code": "AE", "name": "만다린 항공"},
  {"code": "7Y", "name": "만야다나폰 항공"},
  {"code": "NR", "name": "만타 에어"},
  {"code": "DB", "name": "말레스 항공"},
  {"code": "MH", "name": "말레이시아 항공", "name_en": "Malaysia Airlines"},
  {"code": "VM", "name": "맥스 항공 나이지리아"},
  {"code": "4X", "name": "머큐리 월드 카고"},
  {"code": "BM", "name": "메드스키 항공"},
  {"code": "YV", "name": "메사 항공"},
  {"code": "WD", "name": "모던 로지스틱스"},
  {"code": "Q2", "name": "몰디비안"},
  {"code": "MT", "name": "몰타 메드에어"},
  {"code": "XF", "name": "몽골 화물항공"},
  {"code": "ME", "name": "미들 이스트 항공"},
  {"code": "M4", "name": "미스트랄 항공"},
  {"code": "UB", "name": "미얀마 국영항공"},
  {"code": "8M", "name": "미얀마 국제항공"},
  {"code": "J4", "name": "바드르 항공"},
  {"code": "ID", "name": "바틱 에어 인도네시아"},
  {"code": "PG", "name": "방콕항공"},
  {"code": "VK", "name": "밸류제트"},
  {"code": "QH", "name": "뱀부 항공"},
  {"code": "NB", "name": "버니크 항공"},
  {"code": "J8", "name": "버자야 에어"},
  {"code": "RR", "name": "버즈"},
  {"code": "VS", "name": "버진 애틀랜틱 항공", "name_en": "Virgin Atlantic"},
  {"code": "VA", "name": "버진 오스트레일리아"},
  {"code": "BD", "name": "버짓 라인"},
  {"code": "8E", "name": "베링항공"},
  {"code": "CH", "name": "베미지 항공"},
  {"code": "JV", "name": "베어스킨 항공사"},
  {"code": "VN", "name": "베트남 항공", "name_en": "Vietnam Airlines"},
  {"code": "0V", "name": "베트남 항공 서비스"},
  {"code": "AB", "name": "본자항공"},
  {"code": "VI", "name": "볼가-드뇌프르 항공"},
  {"code": "N3", "name": "볼라리스 엘살바도르"},
  {"code": "Q6", "name": "볼라리스 코스타리카"},
  {"code": "Y4", "name": "볼라리스 항공"},
  {"code": "V7", "name": "볼로테아"},
  {"code": "OB", "name": "볼리비아 항공"},
  {"code": "2L", "name": "볼리비아 항공 운송"},
  {"code": "U4", "name": "부다 에어"},
  {"code": "UZ", "name": "부라키 항공"},
  {"code": "VY", "name": "부엘링 항공"},
  {"code": "B3", "name": "부탄 항공"},
  {"code": "4B", "name": "부티크 에어"},
  {"code": "JD", "name": "북경수도항공"},
  {"code": "FB", "name": "불가리아 항공"},
  {"code": "TF", "name": "브라덴스 지역항공"},
  {"code": "NT", "name": "브라바 항공"},
  {"code": "TT", "name": "브라텐스 국제항공"},
  {"code": "1X", "name": "브랜슨 에어 익스프레스"},
  {"code": "SN", "name": "브뤼셀 항공"},
  {"code": "MX", "name": "브리즈 항공"},
  {"code": "SI", "name": "블루 아일랜드"},
  {"code": "BG", "name": "비만 방글라데시 항공"},
  {"code": "VB", "name": "비바 에어로버스"},
  {"code": "V4", "name": "비에케스 에어링크"},
  {"code": "VJ", "name": "비엣젯 항공", "name_en": "VietJet Air"},
  {"code": "B4", "name": "비온드 항공"},
  {"code": "UQ", "name": "비즈니스 항공 센터"},
  {"code": "OL", "name": "사모아 에어웨이"},
  {"code": "SV", "name": "사우디아 항공", "name_en": "Saudia"},
  {"code": "S1", "name": "사우리야항공"},
  {"code": "WN", "name": "사우스웨스트 항공", "name_en": "Southwest Airlines"},
  {"code": "2S", "name": "사우스윈드 항공"},
  {"code": "9R", "name": "사테나 항공"},
  {"code": "ZF", "name": "사파리 익스프레스 카고"},
  {"code": "FA", "name": "사페어"},
  {"code": "OV", "name": "살람 에어"},
  {"code": "SO", "name": "살사 다아이티"},
  {"code": "FM", "name": "상해 항공"},
  {"code": "MF", "name": "샤먼 항공"},
  {"code": "SH", "name": "샤프 항공"},
  {"code": "CE", "name": "샬레어 항공"},
  {"code": "PL", "name": "서던에어 차터"},
  {"code": "SY", "name": "선 컨트리 항공"},
  {"code": "R8", "name": "선댄스 항공 베네수엘라"},
  {"code": "SR", "name": "선데어"},
  {"code": "2U", "name": "선도르 국제항공"},
  {"code": "S6", "name": "선라이즈 항공"},
  {"code": "YH", "name": "선스플래시 항공 LLC"},
  {"code": "WG", "name": "선윙 항공"},
  {"code": "ZH", "name": "선전 항공"},
  {"code": "XU", "name": "섬에어"},
  {"code": "ER", "name": "세린 에어"},
  {"code": "D2", "name": "세버스탈 에어컴퍼니"},
  {"code": "5J", "name": "세부 퍼시픽 항공", "name_en": "Cebu Pacific"},
  {"code": "DG", "name": "세브고"},
  {"code": "K3", "name": "세이프 에어 컴퍼니"},
  {"code": "PV", "name": "세인트바스 커뮤터"},
  {"code": "IS", "name": "세페란항공"},
  {"code": "9M", "name": "센터럴 마운틴에어"},
  {"code": "5Z", "name": "셈에어"},
  {"code": "SZ", "name": "소몬에어"},
  {"code": "FW", "name": "솔렌타 항공 모잠비크"},
  {"code": "IE", "name": "솔로몬 항공"},
  {"code": "DR", "name": "수난 루이리 항공"},
  {"code": "SD", "name": "수단 항공"},
  {"code": "PY", "name": "수리남 항공"},
  {"code": "Y8", "name": "수파르나 항공"},
  {"code": "N9", "name": "슈리 항공"},
  {"code": "IU", "name": "슈퍼에어 제트"},
  {"code": "6Y", "name": "스마트링스 항공"},
  {"code": "2N", "name": "스마트링스 항공 몰타"},
  {"code": "QS", "name": "스마트윙스"},
  {"code": "6D", "name": "스마트윙스 슬로바키아"},
  {"code": "3Z", "name": "스마트윙스 폴란드"},
  {"code": "7O", "name": "스마트윙스 헝가리"},
  {"code": "2E", "name": "스모키베이 에어"},
  {"code": "LX", "name": "스위스 국제 항공", "name_en": "Swiss International Air Lines"},
  {"code": "WT", "name": "스위프트에어"},
  {"code": "Y3", "name": "스카이 KG 항공"},
  {"code": "3E", "name": "스카이 셔틀 헬리콥터스 리미티드"},
  {"code": "GQ", "name": "스카이 익스프레스"},
  {"code": "S8", "name": "스카이 항공"},
  {"code": "QU", "name": "스카이라인 익스프레스"},
  {"code": "GG", "name": "스카이리스 카고"},
  {"code": "BC", "name": "스카이마크 항공", "name_en": "Skymark Airlines"},
  {"code": "PQ", "name": "스카이업"},
  {"code": "U5", "name": "스카이업 MT"},
  {"code": "OW", "name": "스카이워드 익스프레스"},
  {"code": "OO", "name": "스카이웨스트 항공"},
  {"code": "TE", "name": "스카이택시"},
  {"code": "DO", "name": "스카이하이 도미니카나"},
  {"code": "DV", "name": "스캇 항공"},
  {"code": "HK", "name": "스키퍼스 항공"},
  {"code": "S5", "name": "스타 에어 인도"},
  {"code": "JX", "name": "스타룩스 항공"},
  {"code": "4E", "name": "스타보에어"},
  {"code": "4R", "name": "스타이스트 항공"},
  {"code": "7G", "name": "스타플라이어", "name_en": "StarFlyer"},
  {"code": "SG", "name": "스파이스 제트"},
  {"code": "P8", "name": "스프린트 에어"},
  {"code": "C7", "name": "시나몬 에어"},
  {"code": "5G", "name": "시라크 항공"},
  {"code": "RB", "name": "시리아 항공"},
  {"code": "BB", "name": "시본 항공"},
  {"code": "A2", "name": "시엘로스 항공"},
  {"code": "QG", "name": "시티링크"},
  {"code": "WX", "name": "시티제트"},
  {"code": "K5", "name": "실버스톤 항공 서비스"},
  {"code": "US", "name": "실크 아비아"},
  {"code": "7E", "name": "실트 에어"},
  {"code": "SQ", "name": "싱가포르 항공", "name_en": "Singapore Airlines"},
  {"code": "XQ", "name": "썬익스프레스"},
  {"code": "3U", "name": "쓰촨 항공"},
  {"code": "XO", "name": "씨에어 인터내셔널"},
  {"code": "EH", "name": "아나 윙즈"},
  {"code": "AG", "name": "아루바 항공"},
  {"code": "6A", "name": "아르메니아 에어웨이"},
  {"code": "FG", "name": "아리아나 아프간 항공"},
  {"code": "W3", "name": "아리크 항공"},
  {"code": "MZ", "name": "아마쿠사 항공"},
  {"code": "A8", "name": "아메리라이트"},
  {"code": "M6", "name": "아메리제트 인터내셔널"},
  {"code": "AA", "name": "아메리칸 항공", "name_en": "American Airlines"},
  {"code": "XP", "name": "아벨로항공"},
  {"code": "YK", "name": "아비아 트래픽 컴퍼니"},
  {"code": "GU", "name": "아비앙카 과테말라"},
  {"code": "2K", "name": "아비앙카 에콰도르"},
  {"code": "TA", "name": "아비앙카 엘살바도르"},
  {"code": "WC", "name": "아비앙카 온두라스"},
  {"code": "QT", "name": "아비앙카 카고"},
  {"code": "LR", "name": "아비앙카 코스타리카"},
  {"code": "AV", "name": "아비앙카 항공"},
  {"code": "9V", "name": "아비어 항공"},
  {"code": "X8", "name": "아비온 익스프레스 몰타"},
  {"code": "4K", "name": "아스카리 에비에이션"},
  {"code": "KP", "name": "아스키 항공"},
  {"code": "0A", "name": "아스타 항공"},
  {"code": "OZ", "name": "아시아나 항공", "name_en": "Asiana Airlines"},
  {"code": "AM", "name": "아에로 멕시코"},
  {"code": "6R", "name": "아에로 유니온"},
  {"code": "E4", "name": "아에로탁시 아베테"},
  {"code": "FI", "name": "아이슬란드 항공"},
  {"code": "F7", "name": "아이플라이"},
  {"code": "2O", "name": "아일랜드 에어 서비스"},
  {"code": "J2", "name": "아젤바이잔 항공"},
  {"code": "S4", "name": "아조레스 항공"},
  {"code": "AD", "name": "아줄 브라질"},
  {"code": "2F", "name": "아줄 코넥타"},
  {"code": "AJ", "name": "아즈텍 항공"},
  {"code": "QP", "name": "아카사 항공"},
  {"code": "V8", "name": "아트란"},
  {"code": "5Y", "name": "아틀라스 에어"},
  {"code": "RC", "name": "아틀랜틱 에어웨이"},
  {"code": "J7", "name": "아프리제트 비즈니스서비스"},
  {"code": "AW", "name": "아프리카 월드 항공"},
  {"code": "BU", "name": "아프리카 항공"},
  {"code": "8U", "name": "아프리키야 항공"},
  {"code": "6L", "name": "악락 항공"},
  {"code": "O4", "name": "안데스리네아스애리아"},
  {"code": "KO", "name": "알래스카 센트랄 익스프레스"},
  {"code": "J5", "name": "알래스카 시플레인서비스"},
  {"code": "AS", "name": "알래스카 항공", "name_en": "Alaska Airlines"},
  {"code": "JN", "name": "알래스카 항공 교통"},
  {"code": "DQ", "name": "알렉산드리아 항공"},
  {"code": "KH", "name": "알로하 항공 화물"},
  {"code": "VC", "name": "알류샨 항공"},
  {"code": "QQ", "name": "알리앙스 항공"},
  {"code": "AP", "name": "알바스타"},
  {"code": "5A", "name": "알파인 에어 익스프레스"},
  {"code": "2G", "name": "앙공라 항공"},
  {"code": "Q3", "name": "앙구일라 에어서비스"},
  {"code": "IZ", "name": "앨키나 이스라엘 항공"},
  {"code": "R3", "name": "야쿠티아 항공"},
  {"code": "AN", "name": "어드밴스드 에어"},
  {"code": "4W", "name": "얼라이드 에어"},
  {"code": "A3", "name": "에게안 항공", "name_en": "Aegean Airlines"},
  {"code": "WK", "name": "에델바이스 에어"},
  {"code": "EA", "name": "에메랄드항공 아일랜드"},
  {"code": "ET", "name": "에메테베", "name_en": "Ethiopian Airlines"},
  {"code": "EK", "name": "에미레이트 항공", "name_en": "Emirates"},
  {"code": "BR", "name": "에바 항공", "name_en": "EVA Air"},
  {"code": "8K", "name": "에바스 항공"},
  {"code": "5V", "name": "에버츠 항공 화물"},
  {"code": "GD", "name": "에비에어"},
  {"code": "GT", "name": "에어 구이린"},
  {"code": "GL", "name": "에어 그린란드"},
  {"code": "4N", "name": "에어 노스"},
  {"code": "PX", "name": "에어 뉴기니"},
  {"code": "NZ", "name": "에어 뉴질랜드", "name_en": "Air New Zealand"},
  {"code": "EN", "name": "에어 돌로미티"},
  {"code": "GZ", "name": "에어 라로통가"},
  {"code": "7I", "name": "에어 리비아"},
  {"code": "LZ", "name": "에어 링크"},
  {"code": "ZM", "name": "에어 마냐스"},
  {"code": "NX", "name": "에어 마카오"},
  {"code": "KM", "name": "에어 말타"},
  {"code": "MV", "name": "에어 메디티라아난"},
  {"code": "MK", "name": "에어 모리셔스"},
  {"code": "4O", "name": "에어 몬테네그로"},
  {"code": "NF", "name": "에어 바누아투"},
  {"code": "KF", "name": "에어 벨기에"},
  {"code": "2J", "name": "에어 부르키나"},
  {"code": "BX", "name": "에어 부산", "name_en": "Air Busan"},
  {"code": "PJ", "name": "에어 생피에르"},
  {"code": "RS", "name": "에어 서울", "name_en": "Air Seoul"},
  {"code": "HC", "name": "에어 세네갈"},
  {"code": "JU", "name": "에어 세르비아"},
  {"code": "Y2", "name": "에어 센츄리"},
  {"code": "PF", "name": "에어 시알"},
  {"code": "G9", "name": "에어 아라비아"},
  {"code": "3O", "name": "에어 아라비아 모로코"},
  {"code": "3L", "name": "에어 아라비아 아부다비"},
  {"code": "E5", "name": "에어 아라비아 이집트"},
  {"code": "KC", "name": "에어 아스타나"},
  {"code": "2A", "name": "에어 아스트라"},
  {"code": "ZB", "name": "에어 알바니아"},
  {"code": "6I", "name": "에어 알시"},
  {"code": "AH", "name": "에어 알제리"},
  {"code": "TZ", "name": "에어 앙카"},
  {"code": "UU", "name": "에어 오스트랄"},
  {"code": "3N", "name": "에어 우르가"},
  {"code": "ZW", "name": "에어 위스콘신"},
  {"code": "X5", "name": "에어 유로파 익스프레스"},
  {"code": "UX", "name": "에어 유로파 항공"},
  {"code": "3H", "name": "에어 인뉴이트"},
  {"code": "AI", "name": "에어 인디아", "name_en": "Air India"},
  {"code": "IX", "name": "에어 인디아 익스프레스"},
  {"code": "DJ", "name": "에어 지부티"},
  {"code": "UM", "name": "에어 짐바브웨"},
  {"code": "3C", "name": "에어 차트마스"},
  {"code": "2Q", "name": "에어 카고캐리어"},
  {"code": "TX", "name": "에어 카라이브"},
  {"code": "TY", "name": "에어 칼레도니"},
  {"code": "AC", "name": "에어 캐나다", "name_en": "Air Canada"},
  {"code": "RV", "name": "에어 캐나다 루즈"},
  {"code": "KS", "name": "에어 커넥트 항공"},
  {"code": "HF", "name": "에어 코트디부아르"},
  {"code": "YN", "name": "에어 크리벡"},
  {"code": "TN", "name": "에어 타히티 누이"},
  {"code": "ST", "name": "에어 탄루윈"},
  {"code": "TS", "name": "에어 트란삿"},
  {"code": "8C", "name": "에어 트랜스포트 인터내셔널"},
  {"code": "8T", "name": "에어 틴디"},
  {"code": "7P", "name": "에어 파나마"},
  {"code": "AF", "name": "에어 프랑스", "name_en": "Air France"},
  {"code": "F4", "name": "에어 플라맹고"},
  {"code": "P4", "name": "에어 피스"},
  {"code": "HT", "name": "에어 호라이즌"},
  {"code": "LD", "name": "에어 홍콩"},
  {"code": "AO", "name": "에어 후한"},
  {"code": "TL", "name": "에어노스"},
  {"code": "RF", "name": "에어로 K", "name_en": "Aero K"},
  {"code": "KA", "name": "에어로 노마드"},
  {"code": "8G", "name": "에어로 딜리"},
  {"code": "N2", "name": "에어로 콘트렉트 항공"},
  {"code": "3S", "name": "에어로로직"},
  {"code": "KW", "name": "에어로스탄"},
  {"code": "F5", "name": "에어로트렌스카고"},
  {"code": "ZV", "name": "에어루스"},
  {"code": "XZ", "name": "에어리탈리아"},
  {"code": "K2", "name": "에어리프트 알래스카"},
  {"code": "EI", "name": "에어링거스"},
  {"code": "BT", "name": "에어발틱"},
  {"code": "4Y", "name": "에어버스 국제운송"},
  {"code": "RU", "name": "에어브리지카고 항공"},
  {"code": "PA", "name": "에어블루"},
  {"code": "AK", "name": "에어아시아", "name_en": "AirAsia"},
  {"code": "D7", "name": "에어아시아 엑스", "name_en": "AirAsia X"},
  {"code": "ED", "name": "에어익스플로어"},
  {"code": "NQ", "name": "에어재팬"},
  {"code": "KJ", "name": "에어제타"},
  {"code": "JK", "name": "에어카리베"},
  {"code": "EF", "name": "에어카리베 페루"},
  {"code": "SB", "name": "에어칼린"},
  {"code": "P2", "name": "에어케냐"},
  {"code": "YP", "name": "에어프레미아", "name_en": "Air Premia"},
  {"code": "RE", "name": "에어허버항공"},
  {"code": "ZD", "name": "에와 항공"},
  {"code": "VF", "name": "에이젯"},
  {"code": "8J", "name": "에코젯"},
  {"code": "ZU", "name": "에티오피아 모잠비크 항공"},
  {"code": "EY", "name": "에티하드 항공", "name_en": "Etihad Airways"},
  {"code": "9E", "name": "엔더버 항공"},
  {"code": "EL", "name": "엘리항공"},
  {"code": "LY", "name": "엘알 항공"},
  {"code": "BA", "name": "영국 항공", "name_en": "British Airways"},
  {"code": "IY", "name": "예메니아"},
  {"code": "YT", "name": "예티 항공"},
  {"code": "O7", "name": "오렌부르크 항공"},
  {"code": "HZ", "name": "오로라"},
  {"code": "GR", "name": "오리니 에어서비스"},
  {"code": "OC", "name": "오리엔탈 에어 브리지"},
  {"code": "OG", "name": "오리지날에어"},
  {"code": "UI", "name": "오릭스 에어서비스"},
  {"code": "WY", "name": "오만 에어"},
  {"code": "OS", "name": "오스트리안 항공", "name_en": "Austrian Airlines"},
  {"code": "YI", "name": "오야 국제항공"},
  {"code": "BK", "name": "오캐이 항공"},
  {"code": "OA", "name": "올림픽 항공"},
  {"code": "EB", "name": "와모스 항공"},
  {"code": "WP", "name": "와사야 항공"},
  {"code": "R5", "name": "요르단 항공"},
  {"code": "UR", "name": "우간다 항공"},
  {"code": "U6", "name": "우랄 항공"},
  {"code": "HY", "name": "우즈베키스탄 항공"},
  {"code": "OX", "name": "원항공 SAU"},
  {"code": "WL", "name": "월드 아틀랜틱 항공"},
  {"code": "2W", "name": "월드투플라이"},
  {"code": "3P", "name": "월드투플라이 포르투갈"},
  {"code": "KD", "name": "웨스턴 글로벌 항공"},
  {"code": "WS", "name": "웨스트제트"},
  {"code": "WF", "name": "위데뢰에 항공"},
  {"code": "W6", "name": "위즈 에어"},
  {"code": "W4", "name": "위즈 에어 몰타"},
  {"code": "5W", "name": "위즈 에어 아부다비"},
  {"code": "W9", "name": "위즈 에어 영국"},
  {"code": "WH", "name": "윙고 파나마"},
  {"code": "IW", "name": "윙즈 에어"},
  {"code": "UA", "name": "유나이티드 항공", "name_en": "United Airlines"},
  {"code": "B7", "name": "유니 항공"},
  {"code": "U7", "name": "유니월드에어카고"},
  {"code": "6U", "name": "유니크 에어"},
  {"code": "H6", "name": "유럽 항공 차터"},
  {"code": "PS", "name": "유럽 화물항공"},
  {"code": "YU", "name": "유로 애틀랜틱 항공"},
  {"code": "Q4", "name": "유로 항공"},
  {"code": "E6", "name": "유로윙스 유럽 리미티드"},
  {"code": "EW", "name": "유로윙즈"},
  {"code": "YZ", "name": "유얼웨이즈"},
  {"code": "UF", "name": "유엠 항공"},
  {"code": "UT", "name": "유테어 항공"},
  {"code": "IO", "name": "이르에어로"},
  {"code": "E9", "name": "이베로젯"},
  {"code": "I2", "name": "이베리아 익스프레스"},
  {"code": "IB", "name": "이베리아 항공", "name_en": "Iberia"},
  {"code": "E7", "name": "이스타페타 항공"},
  {"code": "ZE", "name": "이스타항공", "name_en": "Eastar Jet"},
  {"code": "T3", "name": "이스턴 에어웨이"},
  {"code": "I8", "name": "이자비아"},
  {"code": "MG", "name": "이즈니스 항공"},
  {"code": "RD", "name": "이지 차터"},
  {"code": "7Z", "name": "이지에어"},
  {"code": "U2", "name": "이지젯", "name_en": "easyJet"},
  {"code": "EC", "name": "이지젯 유럽"},
  {"code": "MS", "name": "이집트항공", "name_en": "EgyptAir"},
  {"code": "QZ", "name": "인도네시아 에어아시아", "name_en": "Indonesia AirAsia"},
  {"code": "6E", "name": "인디고 항공"},
  {"code": "I7", "name": "인디아원 에어"},
  {"code": "8B", "name": "인티라 항공"},
  {"code": "JL", "name": "일본 항공", "name_en": "Japan Airlines"},
  {"code": "JC", "name": "일본 항공 커뮤터"},
  {"code": "KZ", "name": "일본 화물항공"},
  {"code": "J9", "name": "자지라항공"},
  {"code": "JM", "name": "잠보제트"},
  {"code": "ZN", "name": "잠비아 항공"},
  {"code": "RY", "name": "장시 항공"},
  {"code": "JG", "name": "장쑤 징동 화물항공"},
  {"code": "NH", "name": "전일본공수", "name_en": "All Nippon Airways"},
  {"code": "7C", "name": "제주 항공", "name_en": "Jeju Air"},
  {"code": "ZK", "name": "제트 아비아"},
  {"code": "B6", "name": "제트블루 항공", "name_en": "JetBlue"},
  {"code": "JZ", "name": "제트스마트 페루"},
  {"code": "3K", "name": "제트스타 아시아"},
  {"code": "GK", "name": "제트스타 일본", "name_en": "Jetstar Japan"},
  {"code": "JQ", "name": "제트스타 항공", "name_en": "Jetstar Airways"},
  {"code": "GH", "name": "조지아 항공"},
  {"code": "6J", "name": "주바 항공"},
  {"code": "3J", "name": "주바 항공 소말리아"},
  {"code": "HO", "name": "준야오 항공"},
  {"code": "CZ", "name": "중국 남방 항공", "name_en": "China Southern Airlines"},
  {"code": "CO", "name": "중국 노스웨스턴 국제항공"},
  {"code": "MU", "name": "중국 동방 항공", "name_en": "China Eastern Airlines"},
  {"code": "G5", "name": "중국 익스프레스 항공"},
  {"code": "I9", "name": "중국 중앙 항공"},
  {"code": "CK", "name": "중국 화물 항공"},
  {"code": "CI", "name": "중화 항공", "name_en": "China Airlines"},
  {"code": "XM", "name": "지멕스 항공"},
  {"code": "D4", "name": "지오스카이"},
  {"code": "LJ", "name": "진에어", "name_en": "Jin Air"},
  {"code": "ZG", "name": "집 에어"},
  {"code": "X7", "name": "챌린지 항공"},
  {"code": "5C", "name": "챌린지 항공 IL"},
  {"code": "GS", "name": "천진 항공"},
  {"code": "GM", "name": "체어항공 AG"},
  {"code": "9C", "name": "춘추 항공"},
  {"code": "OQ", "name": "충칭 항공"},
  {"code": "QW", "name": "칭다오 항공"},
  {"code": "C3", "name": "카고 쓰리"},
  {"code": "CV", "name": "카고룩스 국제항공"},
  {"code": "W8", "name": "카고제트 항공"},
  {"code": "PM", "name": "카나리플라이 항공"},
  {"code": "HH", "name": "카나트 샤크 항공"},
  {"code": "BW", "name": "카리브 항공"},
  {"code": "QC", "name": "카메룬 항공"},
  {"code": "Z7", "name": "카멕스항공"},
  {"code": "IQ", "name": "카자흐 항공"},
  {"code": "QR", "name": "카타르 항공", "name_en": "Qatar Airways"},
  {"code": "VR", "name": "카페베르데 항공"},
  {"code": "K9", "name": "칼리타 차터"},
  {"code": "MO", "name": "캄 에어"},
  {"code": "K6", "name": "캄보디아 앙코르 항공"},
  {"code": "KR", "name": "캄보디아 항공"},
  {"code": "5T", "name": "캐나다 북부 항공"},
  {"code": "AU", "name": "캐나다 제트라인"},
  {"code": "CX", "name": "캐세이퍼시픽 항공", "name_en": "Cathay Pacific"},
  {"code": "6C", "name": "컨넥트 화물항공"},
  {"code": "LF", "name": "컨투어 항공"},
  {"code": "KQ", "name": "케냐 항공", "name_en": "Kenya Airways"},
  {"code": "QB", "name": "케심 항공"},
  {"code": "KX", "name": "케이맨 항공"},
  {"code": "9K", "name": "케이프 항공"},
  {"code": "M5", "name": "켄모어 에어"},
  {"code": "CD", "name": "코렌돈 네덜란드 항공"},
  {"code": "XC", "name": "코렌돈 항공"},
  {"code": "XR", "name": "코렌돈 항공 유럽"},
  {"code": "SS", "name": "코르스에어"},
  {"code": "CM", "name": "코파 항공"},
  {"code": "P5", "name": "코파 항공 콜롬비아"},
  {"code": "DE", "name": "콘도르 플루그디엔스트"},
  {"code": "V0", "name": "콘비아사"},
  {"code": "8Z", "name": "콩고 항공"},
  {"code": "QF", "name": "콴타스 항공", "name_en": "Qantas"},
  {"code": "CU", "name": "쿠바 항공"},
  {"code": "KU", "name": "쿠웨이트 항공"},
  {"code": "KY", "name": "쿤밍 항공"},
  {"code": "QO", "name": "퀵젯 항공"},
  {"code": "QA", "name": "퀸 빌키스 항공"},
  {"code": "KV", "name": "크라스아비아"},
  {"code": "C8", "name": "크로노스 항공"},
  {"code": "OU", "name": "크로아티아 항공"},
  {"code": "VE", "name": "클릭 에어"},
  {"code": "KG", "name": "키라임 에어"},
  {"code": "Z3", "name": "타나나 에어서비스"},
  {"code": "3T", "name": "타르코 항공"},
  {"code": "SF", "name": "타실리 항공"},
  {"code": "VZ", "name": "타이 비엣젯 항공"},
  {"code": "FD", "name": "타이 에어아시아"},
  {"code": "XJ", "name": "타이 에어아시아 X"},
  {"code": "TG", "name": "타이 항공", "name_en": "Thai Airways"},
  {"code": "IT", "name": "타이거에어 타이완", "name_en": "Tigerair Taiwan"},
  {"code": "ZT", "name": "타이탄 항공"},
  {"code": "HJ", "name": "타즈만 카고 항공"},
  {"code": "TI", "name": "테일윈드 항공"},
  {"code": "TQ", "name": "테일윈드 항공 서비스"},
  {"code": "T9", "name": "투르피알 항공"},
  {"code": "U8", "name": "투스 항공"},
  {"code": "TU", "name": "튀니지 항공"},
  {"code": "UG", "name": "튀니지 항공 익스프레스"},
  {"code": "M8", "name": "트랜스 몰디비안 항공"},
  {"code": "T7", "name": "트랜스글로벌항공"},
  {"code": "HV", "name": "트랜스아비아"},
  {"code": "TO", "name": "트랜스아비아 프랑스"},
  {"code": "R2", "name": "트랜스에어 세네갈"},
  {"code": "TJ", "name": "트레이드윈드 항공"},
  {"code": "9N", "name": "트로픽 항공"},
  {"code": "IL", "name": "트리가나 에어"},
  {"code": "TD", "name": "트빌리시 항공"},
  {"code": "TW", "name": "티웨이 항공", "name_en": "T'way Air"},
  {"code": "5P", "name": "파노라마 항공"},
  {"code": "ZP", "name": "파라네어"},
  {"code": "WE", "name": "파라타항공"},
  {"code": "P6", "name": "파스칸 항공"},
  {"code": "PK", "name": "파키스탄 국제항공"},
  {"code": "OP", "name": "패션에어"},
  {"code": "8Y", "name": "팬퍼시픽 항공"},
  {"code": "P1", "name": "퍼블릭차터닷컴"},
  {"code": "8P", "name": "퍼시픽 코스탈 항공"},
  {"code": "PC", "name": "페가수스 항공"},
  {"code": "FX", "name": "페덱스"},
  {"code": "FN", "name": "페스트젯 짐바브웨"},
  {"code": "DP", "name": "포베다 항공"},
  {"code": "PD", "name": "포터 항공"},
  {"code": "NI", "name": "포튜갈리아 항공"},
  {"code": "PO", "name": "폴라 에어 카고"},
  {"code": "Z4", "name": "푸마 항공"},
  {"code": "FU", "name": "푸저우 항공"},
  {"code": "6P", "name": "프라단 에어 익스프레스"},
  {"code": "BF", "name": "프렌치 비"},
  {"code": "F9", "name": "프론티어 항공"},
  {"code": "4F", "name": "프리덤 항공"},
  {"code": "3X", "name": "프리미어 트랜스 에어"},
  {"code": "MI", "name": "프리버드 유럽"},
  {"code": "FH", "name": "프리버드 항공"},
  {"code": "PW", "name": "프리시즌 항공서비스"},
  {"code": "SX", "name": "플라이 GTA 항공"},
  {"code": "WV", "name": "플라이 나미비아"},
  {"code": "XY", "name": "플라이 나스"},
  {"code": "5M", "name": "플라이 몬세라트"},
  {"code": "S9", "name": "플라이 빅"},
  {"code": "8W", "name": "플라이 올웨이즈"},
  {"code": "F0", "name": "플라이 요르단"},
  {"code": "5F", "name": "플라이 원"},
  {"code": "9P", "name": "플라이 진나"},
  {"code": "FP", "name": "플라이 펠리칸"},
  {"code": "FZ", "name": "플라이두바이"},
  {"code": "FO", "name": "플라이본디"},
  {"code": "F3", "name": "플라이어딜"},
  {"code": "3F", "name": "플라이원 아르메니아"},
  {"code": "F6", "name": "플라이투스카이"},
  {"code": "YS", "name": "플라이트 링크"},
  {"code": "PU", "name": "플러스 울트라 항공"},
  {"code": "W2", "name": "플렉스플라이트"},
  {"code": "PT", "name": "피드 몬트 항공"},
  {"code": "FJ", "name": "피지 항공", "name_en": "Fiji Airways"},
  {"code": "MM", "name": "피치 항공", "name_en": "Peach Aviation"},
  {"code": "AY", "name": "핀 에어", "name_en": "Finnair"},
  {"code": "HI", "name": "필리핀 그랜드캐년 헬리콥터"},
  {"code": "Z2", "name": "필리핀 에어아시아"},
  {"code": "PR", "name": "필리핀 항공", "name_en": "Philippine Airlines"},
  {"code": "HA", "name": "하와이안 항공", "name_en": "Hawaiian Airlines"},
  {"code": "5K", "name": "하이 플라이"},
  {"code": "HU", "name": "하이난 항공"},
  {"code": "HG", "name": "하이버니언 항공"},
  {"code": "H4", "name": "하이스카이 루마니아"},
  {"code": "H7", "name": "하이스카이 몰도바"},
  {"code": "HR", "name": "한에어라인"},
  {"code": "NS", "name": "허베이 항공"},
  {"code": "HN", "name": "헤스톤 항공"},
  {"code": "H3", "name": "헬로젯"},
  {"code": "JB", "name": "헬리제트 인터내셔널"},
  {"code": "5Q", "name": "홀리데이 유럽"},
  {"code": "HD", "name": "홀리데이 항공"},
  {"code": "UO", "name": "홍콩 익스프레스"},
  {"code": "HX", "name": "홍콩 항공", "name_en": "Hong Kong Airlines"},
  {"code": "RH", "name": "홍콩 화물항공"},
  {"code": "JH", "name": "후지드림 항공"},
  {"code": "MR", "name": "훈누 항공"},
  {"code": "H9", "name": "히말라야 항공"},
  {"code": "OI", "name": "힌터렌드 항공"},
];

/** CSV 표기는 '에어 서울'처럼 띄어쓰기가 섞여 있어, 비교 시 공백을 무시한다. */
const squash = (value: string) => value.replace(/\s+/g, "").toLowerCase();

/** 입력한 이름과 일치하는 항공사(코드 자동 채움용). 띄어쓰기는 무시한다. */
export function findAirlineByName(name: string): AirlineOption | undefined {
  const key = squash(name);
  if (!key) return undefined;
  return AIRLINES.find((airline) => squash(airline.name) === key);
}

/**
 * 입력어로 항공사를 검색한다. 국문명 · 영문명 · IATA 코드로 찾으며,
 * 코드가 정확히 맞거나 앞글자가 일치하는 항목을 먼저 보여준다.
 * ('대한' -> 대한항공 KE / 'KE' -> 대한항공 KE / 'korean' -> 대한항공 KE)
 */
export function searchAirlines(query: string, limit = 6): AirlineOption[] {
  const keyword = query.trim();
  if (!keyword) return [];

  const upper = keyword.toUpperCase();
  const key = squash(keyword);
  const exact: AirlineOption[] = [];
  const prefix: AirlineOption[] = [];
  const partial: AirlineOption[] = [];

  for (const airline of AIRLINES) {
    const name = squash(airline.name);
    const nameEn = squash(airline.name_en ?? "");
    if (airline.code === upper) {
      exact.push(airline);
    } else if (name.startsWith(key) || (nameEn && nameEn.startsWith(key))) {
      prefix.push(airline);
    } else if (name.includes(key) || (nameEn && nameEn.includes(key))) {
      partial.push(airline);
    }
  }
  return [...exact, ...prefix, ...partial].slice(0, limit);
}
